// hola
const verbIregulares = [
    "accept",
    "add",
    "admit",
    "allow",
    "agree",
    "answer",
    "arrive",
    "appear",
    "ask",
    "believe",
    "belong",
    "brush",
    "call",
    "cancel",
    "change",
    "clean",
    "close",
    "complain",
    "complete",
    "cook",
    "copy",
]